package net.engawapg.app.viewonlyviewer.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006879)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFa2eeff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f26)
val md_theme_light_secondary = Color(0xFF4b6268)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcde7ee)
val md_theme_light_onSecondaryContainer = Color(0xFF051f24)
val md_theme_light_tertiary = Color(0xFF555d7e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFdbe1ff)
val md_theme_light_onTertiaryContainer = Color(0xFF121a37)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfe)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfe)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdbe4e7)
val md_theme_light_onSurfaceVariant = Color(0xFF3f484b)
val md_theme_light_outline = Color(0xFF70797b)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f2)
val md_theme_light_inverseSurface = Color(0xFF2e3132)
val md_theme_light_inversePrimary = Color(0xFF53d7f1)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF53d7f1)
val md_theme_dark_onPrimary = Color(0xFF003640)
val md_theme_dark_primaryContainer = Color(0xFF004e5b)
val md_theme_dark_onPrimaryContainer = Color(0xFFa2eeff)
val md_theme_dark_secondary = Color(0xFFb2cbd2)
val md_theme_dark_onSecondary = Color(0xFF1c3439)
val md_theme_dark_secondaryContainer = Color(0xFF334a50)
val md_theme_dark_onSecondaryContainer = Color(0xFFcde7ee)
val md_theme_dark_tertiary = Color(0xFFbec5eb)
val md_theme_dark_onTertiary = Color(0xFF272f4d)
val md_theme_dark_tertiaryContainer = Color(0xFF3d4565)
val md_theme_dark_onTertiaryContainer = Color(0xFFdbe1ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe1e3e4)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe1e3e4)
val md_theme_dark_surfaceVariant = Color(0xFF3f484b)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc8cb)
val md_theme_dark_outline = Color(0xFF899295)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e4)
val md_theme_dark_inversePrimary = Color(0xFF006879)
val md_theme_dark_shadow = Color(0xFF000000)

//val seed = Color(0xFFaaeeff)